project_id = "umkizxftwrwqiiahjbrr"

[functions.cancel-order]
verify_jwt = false
[functions.ai-chatbot]
verify_jwt = false
[functions.mercadopago-webhook]
verify_jwt = false
[functions.get-pending-enrollments]
verify_jwt = false
[functions.finalize-enrollment]
verify_jwt = false
[functions.manage-secretary-users]
verify_jwt = false